name: sdoh_prediction_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.0
  - numpy=2.2.6
  - scikit-learn=1.7.0
  - xgboost>=2.0.0
  - joblib=1.5.1
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scipy=1.16.0
  - tqdm>=4.62.0
  - typing-extensions>=4.0.0
  - pip
  - pip:
    - shap>=0.48.0
    - optuna>=3.0.0
    - fairlearn>=0.10.0